services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: my-web-app:latest
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: ore-no-backend:latest
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: my-proxy:latest
    ports:
      - "80:80"